version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/emt_shop
      - SPRING_DATASOURCE_USERNAME=emt
      - SPRING_DATASOURCE_PASSWORD=emt
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - emt-network

  postgres:
    image: postgres:15
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_DB=emt_shop
      - POSTGRES_USER=emt
      - POSTGRES_PASSWORD=emt
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - emt-network

networks:
  emt-network:
    driver: bridge

volumes:
  postgres-data: